twig:
    default_path: '%kernel.project_dir%/templates'
<<<<<<< HEAD
    form_themes: ['bootstrap_4_layout.html.twig']
=======
>>>>>>> 9bfb396 (reprise30042023)

when@test:
    twig:
        strict_variables: true
